name: date_x
description: A lightweight Dart library for date manipulation and formatting.
version: 1.0.0
license: MIT

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
